-run_mode=true
 #"程序的运行模式，false-调试，true-发布"
-log_file=/chatsystem/logs/file.log
 #"发布模式下，用于指定日志的输出文件"
-log_level=0
 #"发布模式下，用于指定日志输出等级"

-registry_host=http://192.168.22.129:2379
 #"服务注册中心地址"
-base_service=/service
 #"服务监控根目录"
-file_service=/service/file_service
 #"文件管理子服务名称"
-friend_service=/service/friend_service
 #"好友管理子服务名称"
-message_service=/service/message_service
 #"消息存储子服务名称"
-speech_service=/service/speech_service
 #"语音识别子服务名称"
-transmite_service=/service/transmite_service
 #"消息转发子服务名称"
-user_service=/service/user_service
 #"用户管理子服务名称"

-redis_host=192.168.22.129
 #"Redis服务器访问地址"
-redis_port=6379
 #"Redis服务器访问端口"
-redis_db=0
 #"Redis默认库号"
-redis_keep_alive=true
 #"Redis长连接保活选项"

-http_listren_port=9000
 #"HTTP服务器监听端口"
-websocket_listren_port=9001
 #"Websocket服务器监听端口"


