-run_mode=true
 #"程序的运行模式，false-调试，true-发布"
-log_file=/chatsystem/logs/file.log
 #"发布模式下，用于指定日志的输出文件"
-log_level=0
 #"发布模式下，用于指定日志输出等级"

-registry_host=http://192.168.22.129:2379
 #"服务注册中心地址"
-base_service=/service
 #"服务监控根目录"
-instance_name=/user_service/instance
 #"当前实例名称"
-access_host=192.168.22.129:10003
 #"当前实例的外部访问地址"

-listen_port=10003
 #"Rpc服务器监听端口"
-rpc_timeout=-1
 #"Rpc调用超时时间"
-rpc_threads=1
 #"Rpc的IO线程数量"

-es_host=http://192.168.22.129:9200/
 #"ES搜索引擎服务器URL"

-mysql_user=root
 #"Mysql服务器访问用户名"
-mysql_password=2162627569
 #"Mysql服务器访问密码"
-mysql_host=192.168.22.129
 #"Mysql服务器访问地址"
-mysql_db=chat_system
 #"Mysql默认库名称"
-mysql_cset=utf8
 #"Mysql客户端字符集"
-mysql_port=0
 #"Mysql服务器访问端口"
-mysql_conn_pool_count=4
 #"Mysql连接池最大连接数量"

-redis_host=192.168.22.129
 #"Redis服务器访问地址"
-redis_port=6379
 #"Redis服务器访问端口"
-redis_db=0
 #"Redis默认库号"
-redis_keep_alive=true
 #"Redis长连接保活选项"

-file_service=/service/file_service
 #"文件管理子服务名称"