# 声明基础镜像来源
FROM ubuntu:22.04
# 声明工作路径
WORKDIR /chatsystem
RUN mkdir -p /chatsystem/bin &&\
    mkdir -p /chatsystem/data &&\
    mkdir -p /chatsystem/logs &&\
    mkdir -p /chatsystem/conf

# 将可执行程序文件，拷贝进入镜像
COPY ./build/message_server /chatsystem/bin
# 将可执行程序依赖，拷贝进入镜像
COPY ./depends /lib/x86_64-linux-gnu/
COPY ./nc /bin
# 设置容器的启动默认操作 --- 运行程序
CMD /chatsystem/bin/message_server -flagfile=/chatsystem/conf/message_server.conf
# CMD ["tail", "-f", "/dev/null"]
